### ISSUE TITLE
ListView support

### ISSUE THREAD

**Issue by oblador** [Shuangzuan/RCTRefreshControl#1]
The most common use for pull to refresh is to combine it with a TableView/ListView, but there doesn't seem to be a good way to do it with this component. 

In RN a ListView actually is a ScrollView but with some added functionality so it shouldn't be too hard. Currently I wrap it with a View and put the `refreshControl` outside of the ListView. It works, but doesn't show the "Pull down", "Release" etc hints.

**Comment by Shuangzuan** [comment]
Thank you for your question. I update the README.md for ListView integration and fix some bug in this situation.
