### ISSUE TITLE
React Native 0.10-rc NSNumber

### ISSUE THREAD

**Issue by exentrich** [Shuangzuan/RCTRefreshControl#14]
**React Native 0.10-rc have breaking changes**:
NSNumber parameters must be marked nonnull: Native bridge methods that take NSNumber values must annotate them using the Objective-C nonnull keyword

**Comment by AdamBrodzinski** [comment]
+1 please merge this as soon as possible. Manually changing works for me.

**Comment by mfkp** [comment]
+1 on this, just ran into same error

**Comment by yelled3** [comment]
@Shuangzuan this was merged but the npm module wasn't updated.
please up to `"version": "2.0.6"`
