### ISSUE TITLE
Hard blink after releasing

### ISSUE THREAD

**Issue by umhan35** [Shuangzuan/RCTRefreshControl#2]
Hi Shuangzuan, thanks for open-sourcing this code. I was very excited to try it but found a "smooth" issue similar to jsdf/react-native-refreshable-listview#8.

![nxvn0a](https://cloud.githubusercontent.com/assets/3271612/7827866/daaa6afc-03f1-11e5-9bbf-8a2078db417a.gif)

As you can see, after releasing, the `renderHeader` quickly push down. This is particularly apparent when there is background color for rows. I guess it's because the `marginTop` value is suddenly changed after releasing.

Here is the code I slightly changed based on the ListView example (the only change is adding color in the `renderRow` anonymous function):

``` JS
'use strict';

var React = require('react-native');
var TimerMixin = require('react-timer-mixin');
var RefreshControl = require('react-refresh-control');
var {
  AppRegistry,
  ListView,
  StyleSheet,
  Text,
  View,
} = React;

var AwesomeProject = React.createClass({
  mixins: [TimerMixin, RefreshControl.Mixin],
  getInitialState: function() {
    var ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
    return {
      dataSource: ds.cloneWithRows(['row 1', 'row 2']),
    };
  },
  componentDidMount: function() {
    this.configureRefreshControl({
      beginRefreshing: () => {
        this.setTimeout(() => {
          this.endRefreshing();
        }, 3000);
      }
    });
  },
  render: function() {
    return (
      <ListView
        style={{marginTop: 20}}
        dataSource={this.state.dataSource}
        renderRow={(rowData) => <Text style={{backgroundColor: 'blue', color: 'white'}}>{rowData}</Text>}
        renderHeader={this.refreshControl}
        {...this.refreshControlProps()}
      />
    );
  }
});

AppRegistry.registerComponent('rn', () => AwesomeProject);

```

**Comment by Shuangzuan** [comment]
I'll push a new version later to solve these issues. Thank you for your question.
