### ISSUE TITLE
Android version ?

### ISSUE THREAD

**Issue by jbrodriguez** [Shuangzuan/RCTRefreshControl#20]
Hi @Shuangzuan, have you given any thought to implementing the Android version of this control ?

**Comment by FaridSafi** [comment]
+1

**Comment by PhilippKrone** [comment]
This would definitely be nice! :)

**Comment by jbrodriguez** [comment]
The React Native team is working on a Refresh control for Android (https://github.com/facebook/react-native/issues/3325#issuecomment-148526112).

But, somebody has already implemented it, as part of a project, but it's not difficult to isolate and replicate in other projects (https://github.com/facebook/react-native/issues/3325#issuecomment-150604844)

**Comment by roysG** [comment]
any updates?
