### ISSUE TITLE
Build error - Semantic Issue

### ISSUE THREAD

**Issue by maggerbo** [Shuangzuan/RCTRefreshControl#5]
After following the instructions i get a build error.
![skaermbillede 2015-06-04 kl 14 29 46](https://cloud.githubusercontent.com/assets/1537181/7984046/2f038478-0ac6-11e5-9d5b-b38a53b93db7.png)

The react-refresh-control folder is outside the react-native folder, is this correct or did I install it wrong.
Any input is appreciated!

I hope you can help, I would love to use your library.

**Comment by Shuangzuan** [comment]
Hello @maggerbo 
If you assume all that things are right. Check the version of the React Native. This library based on 0.4.4.
You can test this library though following steps:
1. Run `npm install -g react-native-cli` in your terminal.
2. Run `react-native init AwesomeProject` in your terminal.
3. And run `cd AwesomeProject`.
4. Then `npm install react-refresh-control`.
5. Drag RCTRefreshControl.xcodeproj to your project on Xcode. Click on your main project file (the one that represents the .xcodeproj) select Build Phases and drag libRCTRefreshControl.a from the Products folder inside the RCTRefreshControl.xcodeproj.
6. Finally copy the `README.md` sample code to your `index.ios.js` (Do not forget modify the project name).

**Comment by maggerbo** [comment]
Thanks!

I needed to upgrade my React Native version. Sorry for the inconvenience!

Med venlig hilsen,

Mathias Aggerbo
Webloftet
Mobil: 4091 9255
http://webloftet.dk
