### ISSUE TITLE
react-native dependecy conflicts with upper level react-native

### ISSUE THREAD

**Issue by sallar** [Shuangzuan/RCTRefreshControl#6]
Hi,

I upgraded my main react-native to 0.5.0 and my app started throwing errors. Found out that react-native which is inside the RCTRefreshControl/node_modules is older so XCode throws errors. Removed that folder and compiled and it was fine.

I wasted 3 hours debugging :-)

**Comment by cgarvis** [comment]
Setting `react-native` as a [peer deependency](http://blog.nodejs.org/2013/02/07/peer-dependencies/) would make debugging this way faster because npm would display an error when the versions are off.

**Comment by booxood** [comment]
Me too ...
:sob:

**Comment by Shuangzuan** [comment]
Solved.
